//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSoundMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreatedBy
    {
        public int Song_ID { get; set; }
        public int Artist_ID { get; set; }
        public bool Perform { get; set; }
        public bool Composse { get; set; }
        public bool Write { get; set; }
    }
}
