//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSoundMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongsAccess
    {
        public bool Display { get; set; }
        public bool Shared_Access { get; set; }
        public int User_ID { get; set; }
        public int Song_ID { get; set; }
    }
}
