//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackSoundMe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public string Permission { get; set; }
        public string Language { get; set; }
        public string Comments { get; set; }
        public string Name { get; set; }
        public string Lyrics { get; set; }
        public string Chords { get; set; }
        public int ID { get; set; }
        public int Published_By_User_ID { get; set; }
    }
}
